### ISSUE TITLE
Import febio_spec 2.5 and export .inp files

### ISSUE THREAD

**Issue by danielcpnkimo** [gibbonCode/GIBBON#28] opened 2018-07-24 18:13 UTC
Hi, recently I wan to import the .feb with named selection and parts from the export of Preview, but I found that both 
"Help_import.feb"  and "DEMO_import_FEB_export_INP" do not support febio_spec 2.5.
Could you add this to the Gibbon codes?

**Comment by Kevin-Mattheus-Moerman** [comment] 2018-07-25 13:12
Thanks for pointing this out. Yes this is currently missing and is on my to do list. Historically I have always abandoned preview so I've always coded models in MATLAB. Therefore I haven't personally had the need to import the FEB files into matlab. I'll try to remove these old demos you've pointed out and will work on a new import function. This may take a while if I have to do it. If others want to do it great and I can help answer questions. 
For the moment, if you send me  your .feb file I can have a look and see if it can be easily coded?

**Comment by Kevin-Mattheus-Moerman** [comment] 2018-07-25 13:14
For the moment I'll flag this as a duplicate of #25 and will close this here.

**Closed by Kevin-Mattheus-Moerman** 2018-07-25 13:14 UTC

**Comment by danielcpnkimo** [comment] 2018-07-25 16:09
Hi, I've attacched my .feb file here. The reason for my using  of Preview is that I want a hex radial biased mesh which is not covered in the help and demo of Gibbon.

[cid:dbc9797c-3eca-4db0-9b68-c20a914b59d4]

I found most of the cylindrical mesh shown in Demo has some defect which may serious influence my result. For example the "DEMO_FEBIO_vessel_fibre_mapping".

[cid:101636de-21cf-491a-9c71-2435f7cbbbc9]

I don't want to generate tetrahedal mesh and I also want to select nodeset of inner and outer layer for prescribing radial boundary condition.

________________________________
